cafemenu/urls.py
from django.urls import path
from .views import HomePage, Contact, CategoryView, CategoryDetailView, ItemsView, ItemsDetailView, item_search
app_name = 'cafemenu'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('contact/', Contact.as_view(), name='contact'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('all-items/', ItemsView.as_view(), name='all_items'),
    path('items/<slug:slug>/', ItemsDetailView.as_view(), name='item_detail'),
    path('search/', item_search, name='item_search'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart

app_name = 'cart'
urlpatterns = [
   path('', cart_detail_view, name='cart_detail'),
   path('add/<int:details_id>/', add_to_cart_view, name='cart_add'),
   path('remove/<int:product_id>/', remove_from_cart, name='cart_remove'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('cafemenu.urls', namespace='cafemenu')),
    # path('report2/', include('data_chart.urls')),
    path('dashbord/', include('dashbord.urls', namespace="dashbord")),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cafemenu/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    sub_image = models.ImageField('category_image', upload_to='category_img/', height_field=None, width_field=None,null=True,blank=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.category_name


class MenuItem(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='menuitem')
    item_name = models.CharField(max_length=150)
    price = models.PositiveIntegerField()
    mojoudi = models.PositiveIntegerField()
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    description = models.TextField(default="")
    main_image = models.ImageField('Menu_Item_Main_Image',  upload_to='menu_item_img/', height_field=None, width_field=None, null=True,blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.item_name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.item_name}'


class Image(models.Model):

    sub_image = models.ImageField('Menu_Item_Image',  upload_to='menu_item_img/', height_field=None, width_field=None, null=True,blank=True)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE, related_name='image')
    
    
# class ShoppingCart(models.Model):
#     item_id = models.ForeignKey(MenuItem, on_delete=models.CASCADE, related_name='shoppingcart')    # ask abolfazl
#     quantity = models.PositiveIntegerField()
#     created_at = models.DateTimeField(auto_now_add=True) # ask abolfazl
#     updated_at = models.DateTimeField(auto_now=True)    # ask abolfazl
#     total_price = models.PositiveIntegerField()

cafemenu/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, TemplateView
from .models import Category, Image, MenuItem
from cart.forms import AddToCartProductForm
from django.db.models import Q, F
# Create your views here.

# class HomePage(TemplateView):
#     template_name = 'cafemenu/main_page.html'
    
class HomePage(ListView):
    model = MenuItem
    template_name = 'cafemenu/main_page.html'
    context_object_name = 'items'
    queryset = MenuItem.objects.prefetch_related('image').order_by('id')[:6]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def item_search(request):
    search_query = request.GET.get('search')
    search = MenuItem.objects.filter(Q(item_name__icontains=search_query) | Q(description__icontains=search_query) | Q(category__category_name__icontains=search_query))
    return render(request, 'cafemenu/search.html', {'searchs': search})

    
class Contact(TemplateView):
    template_name = 'cafemenu/contact.html'

class CategoryView(ListView):
    model = Category
    template_name = 'cafemenu/catrgory.html'
    context_object_name = 'category'
    queryset = Category.objects.all()

class CategoryDetailView(ListView):
    model = MenuItem
    template_name = 'cafemenu/menuitem_list.html'
    context_object_name = 'menu_items'

    def get_queryset(self):
        self.category = Category.objects.get(slug=self.kwargs['slug'])
        return MenuItem.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context
    
class ItemsView(ListView):
    model = MenuItem
    template_name = 'cafemenu/items_list.html'
    context_object_name = 'items'
    queryset = MenuItem.objects.prefetch_related('image')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context
    

class ItemsDetailView(DetailView):
    model = MenuItem
    template_name = 'cafemenu/item_detail_list.html'
    context_object_name = 'details'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['item_name'] = self.object
        description_lines = self.object.description.splitlines()
        context['description_lines'] = description_lines
        context['item_images'] = self.object.image.all()
        context['similar_item'] = MenuItem.objects.filter(category = self.object.category)
        context['add_to_cart_form'] = AddToCartProductForm()
        print(context['similar_item'])
        return context


# def home_page(request):
#     return render(request, 'cafemenu/main_page.html')

# def contact(request):
#     return render(request, 'cafemenu/contact.html')

cafemenu/templates/cafemenu/category_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Category
{% endblock %}


{% block content %}
<div class="jumbotron jumbotron-fluid page-header mb-3">
    <div class="container text-center py-5">
        <h1 class="text-white display-3 mt-lg-5">دسته بندی</h1>
    </div>
</div>
<!-- Header End -->


<!-- Products Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row d-flex align-items-center text-center justify-content-center">
            {% for item in category %}
            <div class="col-lg-3 col-md-6 mb-4 pb-2 d-flex flex-column align-items-center text-center">
                <div class="product-item d-flex flex-column text-center rounded mx-3">
                    <a href="{% url 'cafemenu:category_detail' slug=item.slug %}"
                            class="d-flex mt-4 justify-content-center rounded-circle w-100 h-100"
                            >
                    <div class="position-relative bg-primary rounded-circle mt-n3 mb-4 p-3"
                        style="width: 150px; height: 150px;">
                        <img class="rounded-circle w-100 h-100" src="{{ item.sub_image.url }}"
                            alt="{{ item.category_name }}" style="object-fit: cover;">
                        
                        <h1 class="fs-6 mt-4" style="color: dimgrey;" >{{ item.category_name }}</h1>
                        
                    </div>
                </a>
                </div>
            </div>
            {% endfor %}
            
        </div>
        <div class="row d-flex align-items-center text-center"></div>
        <div class="col-12 text-center">
            <a href="#" class="btn btn-primary py-3 px-5 mt-3">بیشتر</a>
        </div>
    </div>
    </div>
</div>
{% endblock %}

cafemenu/templates/cafemenu/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Contact Us page
{% endblock %}

{% block content %}
    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
        <div class="container text-center py-5">
            <h1 class="text-white display-3 mt-lg-5">Contact</h1>
            <div class="d-inline-flex align-items-center text-white">
                <p class="m-0"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-circle px-3"></i>
                <p class="m-0">Contact</p>
            </div>
        </div>
    </div>
    <!-- Header End -->
    
    <!-- Contact Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <h1 class="section-title position-relative text-center mb-5">Contact Us For Any Query</h1>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-9">
                    <div class="contact-form bg-light rounded p-5">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="form-row">
                                <div class="col-sm-6 control-group">
                                    <input type="text" class="form-control p-4" id="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="col-sm-6 control-group">
                                    <input type="email" class="form-control p-4" id="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control p-4" id="subject" placeholder="Subject" required="required" data-validation-required-message="Please enter a subject" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control p-4" rows="6" id="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block py-3 px-5" type="submit" id="sendMessageButton">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

{% endblock %}

cafemenu/templates/cafemenu/item_detail_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Item Detail
{% endblock %}


{% block content %}
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5" dir="rtl">
            <div class="row text-center">
                <div class="col-md-5">
                    <img class="card-img-top mb-5 mb-md-0" id="mainImage" src="{{ details.main_image.url }}"
                         alt="{{ item_name }}"/>
                    <div class="row mt-3 justify-content-center">
                        {% for image in item_images %}
                            <div class="col-3 mb-3" data-cro-id="pdp-album-open">
                                <img class="img-fluid rounded-5" src="{{ image.sub_image.url }}"
                                     alt="{{ details.item_name }}" width="100%" height="auto"
                                     onclick="changeImage(this.src)"
                                />

                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-5 text-end">
                    <h1 class="display-5 fw-bolder">{{ details.item_name }}</h1>
                    <div class="fs-5 my-4">
                        <span>{{ details.price }}</span>
                    </div>
                    {% for line in description_lines %}
                        <li>{{ line }}</li>
                    {% endfor %}
                    {% comment %} <p class="lead">{{ details.description }}</p> {% endcomment %}
                    <div class="row align-items-center mt-4">
                        {#                        <button class="col-md-1 btn-sm border-0 btn-link"#}
                        {#                            onclick="this.parentNode.querySelector('input[type=number]').stepUp()">#}
                        {#                            <i class="fas fa-plus"></i>#}
                        {#                        </button>#}
                        {#                        <input class="col-md-3 form-control text-center" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />#}
                        {#                        <button class="col-md-1 btn-sm border-0 btn-link"#}
                        {#                            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">#}
                        {#                            <i class="fas fa-minus"></i>#}
                        {#                        </button>#}
                        <form action="{% url 'cart:cart_add' details.id %}" method="post">
                            {% csrf_token %}
                            {{ add_to_cart_form|crispy }}
                            {#                        <button class="btn" type="submit"> اضافه کردن به سبد خرید</button>#}
                            <button class="col-sm-7 btn btn-outline-dark flex-shrink-0 me-3" type="submit">
                                <i class="bi-cart-fill me-1"></i>
                                اضافه کردن به سبد خرید
                            </button>
                        </form>

                    </div>

                </div>
            </div>
        </div>

    </section>

    <!-- Related items section-->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">محصولات مشابه</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for item in similar_item %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src={{ item.main_image.url }} alt="..."/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ item.item_name }}</h5>
                                    <!-- Product reviews-->
                                    {% comment %} <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div> {% endcomment %}
                                    <!-- Product price-->
                                    {{ item.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'cafemenu:item_detail' slug=item.slug %}">اضافه
                                    کردن به سبد خرید</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

cafemenu/templates/cafemenu/items_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    All Items
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
    <div class="container text-center py-5">
        <h1 class="text-white display-3 mt-lg-5">همه‌ی قهوه‌ها</h1>
        <div class="d-inline-flex align-items-center text-white">
            <p class="m-0"><a class="text-white" href="#">خانه</a></p>
            <i class="fa fa-circle px-3"></i>
            {% comment %} <p class="m-0">همه‌ی محصولات</p> {% endcomment %}
        </div>
    </div>
</div>
<!-- Header End -->


<!-- Products Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h1 class="section-title position-relative text-center mb-5">پیشنهادات ما برای عاشقان قهوه</h1>
            </div>
        </div>
        <div class="row">
    {% for item in items  %}
        <div class="col-lg-3 col-md-6 mb-4 pb-2">
            <div class="product-item d-flex flex-column align-items-center text-center bg-light rounded py-5 px-3">
                <div class="bg-primary mt-n5 py-3" style="width: 80px;">
                    <h4 class="font-weight-bold text-white mb-0">{{item.price}}</h4>
                </div>
                <div class="position-relative bg-primary rounded-circle mt-n3 mb-4 p-3" style="width: 150px; height: 150px;">
                {% comment %} {% for image in item.image.all %} 
                    {% if forloop.counter < 2 %}
                        <img class="rounded-circle w-100 h-100" src="{{ image.sub_image.url }}" alt="{{ item_name }}" style="object-fit: cover;">
                    {% endif %}
                {% endfor %} {% endcomment %}
                <img class="rounded-circle w-100 h-100" src="{{ item.main_image.url }}" alt="{{ item_name }}" style="object-fit: cover;">
                </div>
                <h5 class="font-weight-bold mb-4">{{item.item_name}}</h5>
                <a href="{% url 'cafemenu:item_detail' slug=item.slug %}" class="btn btn-sm btn-secondary">سفارش</a>
            </div>
        </div>
    {% endfor %}
    <div class="col-12 text-center">
        <a href="#" class="btn btn-primary py-3 px-5">بیشتر</a>
    </div>
</div>
</div>
</div>
{% endblock %}

cafemenu/templates/cafemenu/menuitem_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Items
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
    <div class="container text-center py-5">
        <h1 class="text-white display-3 mt-lg-5">{{ category.category_name }}</h1>
    </div>
</div>
<!-- Header End -->


<!-- Products Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row">
        {% for item in menu_items %}
        <div class="col-lg-3 col-md-6 mb-4 pb-2">
            <div class="product-item d-flex flex-column align-items-center text-center bg-light rounded py-5 px-3">
                <div class="bg-primary mt-n5 py-3" style="width: 80px;">
                    <h5 class="font-weight-bold text-white mb-0">{{item.price}}</h5>
                </div>
                <div class="position-relative bg-primary rounded-circle mt-n3 mb-4 p-3" style="width: 150px; height: 150px;">
                {% comment %} {% for image in item.image.all %} 
                    {% if forloop.counter < 2 %}
                        <img class="rounded-circle w-100 h-100" src="{{ image.sub_image.url }}" alt="{{ item_name }}" style="object-fit: cover;">
                    {% endif %}
                {% endfor %} {% endcomment %}
                <img class="rounded-circle w-100 h-100" src="{{ item.main_image.url }}" alt="{{ item_name }}" style="object-fit: cover;">
                </div>
                <h5 class="font-weight-bold mb-4">{{item.item_name}}</h5>
                <a href="{% url 'cafemenu:item_detail' slug=item.slug %}" class="btn btn-sm btn-secondary">سفارش</a>
            </div>
        </div>
        {% comment %} <h1>{{item.item_name}}</h1> {% endcomment %}
    {% endfor %}
    <div class="col-12 text-center">
        <a href="#" class="btn btn-primary py-3 px-5">بیشتر</a>
    </div>
</div>
</div>
</div>
{% comment %} <h1>{{ category.category_name }}</h1>
<ul>
    {% for item in menu_items %}
        <li>{{ item.item_name }} - {{ item.price }}</li>
    {% endfor %}
</ul> {% endcomment %}
{% endblock %}

cafemenu/templates/cafemenu/search.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    All Items
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid page-header" style="margin-bottom: 90px;">
    <div class="container text-center py-5">
        <h1 class="text-white display-3 mt-lg-5">همه‌ی قهوه‌ها</h1>
        <div class="d-inline-flex align-items-center text-white">
            <p class="m-0"><a class="text-white" href="#">خانه</a></p>
            <i class="fa fa-circle px-3"></i>
            {% comment %} <p class="m-0">همه‌ی محصولات</p> {% endcomment %}
        </div>
    </div>
</div>
<!-- Header End -->


<!-- Products Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            {% if searchs %}
            <div class="col-lg-6">
                <h1 class="section-title position-relative text-center mb-5">جست و جوی شما </h1>
            </div>
                {% else %}
            	<div class="col-lg-6">
                <h1 class="section-title position-relative text-center mb-5">چیزی یافت نشد . </h1>
            </div>
            {% endif %}
        </div>
        <div class="row">
    {% for item in searchs  %}
        <div class="col-lg-3 col-md-6 mb-4 pb-2">
            <div class="product-item d-flex flex-column align-items-center text-center bg-light rounded py-5 px-3">
                <div class="bg-primary mt-n5 py-3" style="width: 80px;">
                    <h4 class="font-weight-bold text-white mb-0">{{item.price}}</h4>
                </div>
                <div class="position-relative bg-primary rounded-circle mt-n3 mb-4 p-3" style="width: 150px; height: 150px;">
                {% comment %} {% for image in item.image.all %}
                    {% if forloop.counter < 2 %}
                        <img class="rounded-circle w-100 h-100" src="{{ image.sub_image.url }}" alt="{{ item_name }}" style="object-fit: cover;">
                    {% endif %}
                {% endfor %} {% endcomment %}
                <img class="rounded-circle w-100 h-100" src="{{ item.main_image.url }}" alt="{{ item_name }}" style="object-fit: cover;">
                </div>
                <h5 class="font-weight-bold mb-4">{{item.item_name}}</h5>
                <a href="{% url 'cafemenu:item_detail' slug=item.slug %}" class="btn btn-sm btn-secondary">سفارش</a>
            </div>
        </div>
    {% endfor %}
    <div class="col-12 text-center">
        <a href="#" class="btn btn-primary py-3 px-5">بیشتر</a>
    </div>
</div>
</div>
</div>
{% endblock %}