accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.user_login, name='logout'),

]

cafemenu/urls.py
from django.urls import path
from .views import HomePage, Contact, CategoryView, CategoryDetailView, ItemsView, ItemsDetailView, item_search
app_name = 'cafemenu'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('contact/', Contact.as_view(), name='contact'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('all-items/', ItemsView.as_view(), name='all_items'),
    path('items/<slug:slug>/', ItemsDetailView.as_view(), name='item_detail'),
    path('search/', item_search, name='item_search'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart

app_name = 'cart'
urlpatterns = [
   path('', cart_detail_view, name='cart_detail'),
   path('add/<int:details_id>/', add_to_cart_view, name='cart_add'),
   path('remove/<int:product_id>/', remove_from_cart, name='cart_remove'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('cafemenu.urls', namespace='cafemenu')),
    # path('report2/', include('data_chart.urls')),
    path('dashbord/', include('dashbord.urls', namespace="dashbord")),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="fa">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "css/style.css" %}>
    <!-- Favicon -->
    <link href={% static "img/favicon.ico" %} rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href={% static "lib/owlcarousel/assets/owl.carousel.min.css" %} rel="stylesheet">
    <link href={% static "lib/lightbox/css/lightbox.min.css" %} rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href={% static "css/style.css" %} rel="stylesheet">

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="styles"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href={% static "css/styles.css" %} rel="style"/>

</head>
<body>

<!-- header Start -->

<!-- Topbar Start -->
<div class="container-fluid bg-primary py-3 d-none d-md-block">
    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center">
                    {% if user.is_authenticated %}
                        <a class="btn btn-outline-dark d-flex justify-content-center align-items-center text-white pr-3 font-weight-bold fs-5"
                           href="{% url 'accounts:logout' %}">خروج</a>
                        <span class="ms-4 text-white font-weight-bold">  خوش آمدی  {{ user.first_name }}  </span>
                    {% else %}
                        <a class="btn btn-outline-dark me-2 text-white pr-3 font-weight-bold fs-5"
                           href="{% url 'accounts:login' %}">ورود</a>
                        <a class="btn btn-outline-dark text-white pr-3 font-weight-bold fs-5"
                           href="{% url 'accounts:signup' %}">ثبت نام </a>
                    {% endif %}
                </div>
                {% comment %} <div class="d-inline-flex align-items-center">
                        <a class="text-white pr-3" href="#">انتقادات و پیشنهادات</a>
                        <span class="text-white">|</span>
                        <a class="text-white px-3" href="#">کمک</a>
                        <span class="text-white">|</span>
                        <a class="text-white pl-3" href="#">پشتیبانی</a>
                    </div> {% endcomment %}
            </div>
            <div class="col-md-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white px-3" href="#">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-3" href="#">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-3" href="#">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-3" href="#">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white pl-3" href="#">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div class="container-fluid position-relative nav-bar p-0">
    <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow p-lg-0">
            <a href="index.html" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-4 text-primary"><span class="text-secondary"> کافه</span> صورتی</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav ml-auto py-0">
                    <a href="index.html" class="nav-item nav-link ">تماس با ما</a>
                    <a href="about.html" class="nav-item nav-link">گالری </a>
                    <a href="{% url 'cafemenu:category' %}" class="nav-item nav-link">دسته بندی</a>
                </div>
                <a href="index.html" class="navbar-brand mx-5 d-none d-lg-block">
                    <h1 class="m-0 display-4 text-primary"><span class="text-secondary"> کافه </span><span>صورتی</span>
                    </h1>
                </a>
                <div class="navbar-nav mr-auto py-0">
                    <a href="{% url 'cafemenu:all_items' %}" class="nav-item nav-link">محصولات</a>
                    <a href="gallery.html" class="nav-item nav-link">درباره ی ما</a>
                    <a href="{% url 'cafemenu:home' %}" class="nav-item nav-link active"> خانه </a>
                    <form class=" d-flex my-2 my-lg-0 mx-4 " method="get" action="{% url 'cafemenu:item_search' %}">
                        <input class="form-control mr-sm-2 mx-2" type="search" placeholder="Search" aria-label="Search"
                               name="search">
                        <button class="btn btn-outline-dark my-3 my-sm-0" type="submit">search</button>
                    </form>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Navbar End -->

<!-- header End -->

<!-- Body Start -->
<main>
    {% block content %}

    {% endblock content %}
</main>
<!-- Body End -->

<!-- Footer Start -->
<div class="container-fluid footer bg-light py-5" style="margin-top: 90px;">
    <div class="container text-center py-5">
        <div class="row">
            <div class="col-12 mb-4">
                <a href="index.html" class="navbar-brand m-0">
                    <h1 class="m-0 mt-n2 display-4 text-primary"><span
                            class="text-secondary"> کافه </span><span>صورتی</span></h1>
                </a>
            </div>
            <div class="col-12 mb-4">
                <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-twitter"></i></a>
                <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-outline-secondary btn-social mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                <a class="btn btn-outline-secondary btn-social" href="#"><i class="fab fa-instagram"></i></a>
            </div>
            <div class="col-12 mt-2 mb-4">
                <div class="row">
                    <div class="col-sm-6 text-center text-sm-right border-right mb-3 mb-sm-0">
                        <h5 class="font-weight-bold mb-2">راه های رسیدن به ما</h5>
                        <p class="mb-2">انقلاب، خیابان وصال شیرازی، نبش بزرگمهر</p>
                        <p class="mb-0">021-66066066</p>
                    </div>
                    <div class="col-sm-6 text-center text-sm-left">
                        <h5 class="font-weight-bold mb-2">ساعات دسترسی به ما</h5>
                        <p class="mb-2">شنبه تا جمعه : از 8 صبح تا 11 شب</p>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <p class="m-0">&copy;All Rights Reserved. طراحی شده توسط <a href="#" class="font-weight-bold">گروه 1 -
                    مکتب شریف</a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-secondary px-2 back-to-top"><i class="fa fa-angle-double-up">Up</i></a>

<!-- JavaScript Libraries -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src={% static "lib/easing/easing.min.js" %}></script>
<script src={% static "lib/waypoints/waypoints.min.js" %}></script>
<script src={% static "lib/owlcarousel/owl.carousel.min.js" %}></script>
<script src={% static "lib/isotope/isotope.pkgd.min.js" %}></script>
<script src={% static "lib/lightbox/js/lightbox.min.js" %}></script>

<!-- Template Javascript -->
<script src={% static "js/main.js" %}></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<!-- Bootstrap core JS-->
{% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script> {% endcomment %}
<!-- Core theme JS-->
<script src={% static "js/scripts.js" %}></script>

</body>
</html>